name: Build project

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]


jobs:
  
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: my-concurrency-group
      cancel-in-progress: true
    steps:

      - name: test1
        run: |
          if [[ "${{ secrets.ARTIFACTORY_API_KEY }}" == "123" ]];then
            echo "是123"
            echo "1:${{ env.API_KEY }}"
            # 运行代码 A 的逻辑...
          else
            echo "其他"
            echo "2:${{ env.API_KEY }}"
            # 运行代码 B 的逻辑...
          fi
        
        env:

          API_KEY: ${{ secrets.GITHUB_TOKEN }}
